### ISSUE TITLE
Google maps does not show the pointer after entering the address

### ISSUE THREAD

**Issue by mildredcrasto** [vancezhao/Smart-Claim#2]
After entering the address in the google maps and hitting the search button. The pointer is not shown on the screen. The first screen shows how it works in our version and the second screen shot shows how it works in actual google app.

![google maps interface issue](https://cloud.githubusercontent.com/assets/10435586/5646904/59cd3e92-9681-11e4-987a-7e3ac1237089.png)
![actual google apps](https://cloud.githubusercontent.com/assets/10435586/5646909/601efd30-9681-11e4-8cf8-57a0996eb6df.png)

**Comment by vancezhao** [comment]
![snip20150108_1](https://cloud.githubusercontent.com/assets/65173/5657136/49db68f8-9724-11e4-8dd6-94c4cae32ca0.png)

I've add the maker (pointer) aftter clicking search button

**Comment by vancezhao** [comment]
@mildredcrasto Please check it on production.
