### ISSUE TITLE
Datatype as time needed

### ISSUE THREAD

**Issue by mildredcrasto** [vancezhao/Smart-Claim#3]
We need to add a data type as Time enter the exact time of accident. The format can be 08:00 AM/PM.
![datatype_time](https://cloud.githubusercontent.com/assets/10435586/5646977/03cf8cd8-9682-11e4-90ab-ad09bb26f3bb.png)

**Comment by Coralma** [comment]
Hi Mildred, I want to confirm about the time field. Do you means add a new field to input the time? Or the Date field need plus the time ?

**Comment by Coralma** [comment]
New data time field has been added to claim configuration.
