### ISSUE TITLE
Droplist / Select features does not work

### ISSUE THREAD

**Issue by mildredcrasto** [vancezhao/Smart-Claim#5]
I have created a droplist / Select feature for the field Carrier. However, the field is blank after the configuration.
![carrier_droplist_configuration](https://cloud.githubusercontent.com/assets/10435586/5648454/fde46336-968e-11e4-81db-e6f98bb81e08.png)
![blank_droplist](https://cloud.githubusercontent.com/assets/10435586/5648456/01397184-968f-11e4-8518-00854b557cfe.png)

**Comment by Coralma** [comment]
Hi Mildred, This issue is because you set the drop down value to the default value. You should put it into expression. The default value is set the default selection of that.
![expression issue](https://cloud.githubusercontent.com/assets/842458/5659102/25a71428-9747-11e4-965c-51134ffcc4c9.png)

**Comment by Coralma** [comment]
For the expression configuration, You can directly input the Argo,Chubb and without the "" double quotation marks. But I also make our system support the "Argo","Chubb".
